# Converted from the provided kitty.conf
# Original name: carbonfox (modified)
# be aware this is a modified version

[colors]

[colors.primary]
background = "#161616"
foreground = "#f2f4f8"

[colors.cursor]
text = "#161616"
cursor = "#f2f4f8"

[colors.selection]
text = "#f2f4f8"
background = "#2a2a2a"

[colors.normal]
black = "#484848"
red = "#ee5396"
green = "#4242B1"
yellow = "#25be6a"
blue = "#be95ff"
magenta = "#E0E27B"
cyan = "#08bdba"
white = "#dfdfe0"

[colors.bright]
black = "#484848"
red = "#ee5396"
green = "#4242B1"
yellow = "#25be6a"
blue = "#be95ff"
magenta = "#E0E27B"
cyan = "#08bdba"
white = "#dfdfe0"
